LIBRARY IEEE               ;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.NUMERIC_STD.ALL   ;
------------------------------------------------------
PACKAGE basic_package IS
	
	SUBTYPE UINT01  IS STD_LOGIC                    ;
	SUBTYPE UINT02  IS STD_LOGIC_VECTOR( 1 DOWNTO 0);
	SUBTYPE UINT03  IS STD_LOGIC_VECTOR( 2 DOWNTO 0);
	SUBTYPE UINT04  IS STD_LOGIC_VECTOR( 3 DOWNTO 0);
	SUBTYPE UINT05  IS STD_LOGIC_VECTOR( 4 DOWNTO 0);
	SUBTYPE UINT06  IS STD_LOGIC_VECTOR( 5 DOWNTO 0);
	SUBTYPE UINT07  IS STD_LOGIC_VECTOR( 6 DOWNTO 0);
	SUBTYPE UINT08  IS STD_LOGIC_VECTOR( 7 DOWNTO 0);
	SUBTYPE UINT09  IS STD_LOGIC_VECTOR( 8 DOWNTO 0);
	SUBTYPE UINT10  IS STD_LOGIC_VECTOR( 9 DOWNTO 0);
	SUBTYPE UINT11  IS STD_LOGIC_VECTOR(10 DOWNTO 0);
	SUBTYPE UINT12  IS STD_LOGIC_VECTOR(11 DOWNTO 0);
	SUBTYPE UINT13  IS STD_LOGIC_VECTOR(12 DOWNTO 0);
	SUBTYPE UINT15  IS STD_LOGIC_VECTOR(14 DOWNTO 0);
	SUBTYPE UINT14  IS STD_LOGIC_VECTOR(13 DOWNTO 0);
	SUBTYPE UINT16  IS STD_LOGIC_VECTOR(15 DOWNTO 0);
	SUBTYPE UINT22  IS STD_LOGIC_VECTOR(21 DOWNTO 0);
	SUBTYPE UINT24  IS STD_LOGIC_VECTOR(23 DOWNTO 0);
	SUBTYPE UINT32  IS STD_LOGIC_VECTOR(31 DOWNTO 0);
	SUBTYPE INT04K  IS INTEGER RANGE 0 TO 4095     ;
	
	CONSTANT NO_ADDR : UINT12 := (OTHERS => '0');
	
	TYPE PK_STAT IS RECORD
		TYP : UINT03;
		HP  : UINT08;
		ATT : UINT06;
		DEF : UINT06;
	END RECORD;
	
	CONSTANT NOPK_STAT : PK_STAT :=
	(
		TYP =>        "100",
		HP  =>        X"FF",
		ATT => "11" & X"F" ,
		DEF => "11" & X"F"
	);

	CONSTANT LEAF_STAT : PK_STAT :=
	(
		TYP =>        "000", --PLANTA
		HP  =>        X"41", --65
		ATT => "00" & X"B" , --11
		DEF => "00" & X"D"   --13
	);
	CONSTANT ZERA_STAT : PK_STAT :=
	(
		TYP =>        "001", --ELECTRICO
		HP  =>        X"58", --88
		ATT => "00" & X"C" , --12
		DEF => "00" & X"7"   --7
	);
	CONSTANT VAPO_STAT : PK_STAT :=
	(
		TYP =>        "010", --AGUA
		HP  =>        X"82", --130
		ATT => "00" & X"6" , --6
		DEF => "00" & X"6"   --6
	);
	CONSTANT SAND_STAT : PK_STAT :=
	(
		TYP =>        "011", --TIERRA
		HP  =>        X"4B", --75
		ATT => "00" & X"A" , --10
		DEF => "00" & X"B"   --11
	);
	CONSTANT ODDI_STAT : PK_STAT :=
	(
		TYP =>        "000", --PLANTA
		HP  =>        X"2D", --45
		ATT => "00" & X"E" , --14
		DEF => "00" & X"F"   --16
	);
	CONSTANT LAPR_STAT : PK_STAT :=
	(
		TYP =>        "010", -- AGUA
		HP  =>        X"82", --130
		ATT => "00" & X"8" , --8
		DEF => "00" & X"8"   --8
	);
	CONSTANT JOLT_STAT : PK_STAT :=
	(
		TYP =>        "001", --ELECTRICO
		HP  =>        X"41", --65
		ATT => "00" & X"7" , --7
		DEF => "00" & X"6"   --6
	);
	CONSTANT GARC_STAT : PK_STAT :=
	(
		TYP =>        "011", --TIERRA
		HP  =>        X"6C", --108
		ATT => "00" & X"D" , --13
		DEF => "00" & X"9"   --9
	);
	CONSTANT FLAR_STAT : PK_STAT :=
	(
		TYP =>        "100", --FUEGO
		HP  =>        X"41", --65
		ATT => "00" & X"D" , --13
		DEF => "00" & X"6"   --6
	);
	CONSTANT CHAR_STAT : PK_STAT :=
	(
		TYP =>        "100", --FUEGO
		HP  =>        X"4E", --78
		ATT => "00" & X"8" , --8
		DEF => "00" & X"7"   --7
	);

	PURE FUNCTION Slv2Int (INPUT : STD_LOGIC_VECTOR)
	RETURN INTEGER;
	
	PURE FUNCTION Int2Slv (INPUT : INTEGER; LENGTH : NATURAL)
	RETURN STD_LOGIC_VECTOR;
	
END PACKAGE basic_package;
------------------------------------------------------
PACKAGE BODY basic_package IS
	
	PURE FUNCTION Slv2Int (INPUT : STD_LOGIC_VECTOR)
	RETURN INTEGER IS
	BEGIN
		RETURN TO_INTEGER(UNSIGNED(INPUT));
	END Slv2Int;
	
	PURE FUNCTION Int2Slv (INPUT : INTEGER; LENGTH : NATURAL)
	RETURN STD_LOGIC_VECTOR IS
	BEGIN
		RETURN STD_LOGIC_VECTOR(TO_UNSIGNED(INPUT, LENGTH));
	END Int2Slv;
	
END basic_package;
