LIBRARY IEEE               ;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.NUMERIC_STD.ALL   ;
------------------------------------------------------
PACKAGE basic_package IS
	
	SUBTYPE UINT01  IS STD_LOGIC                    ;
	SUBTYPE UINT02  IS STD_LOGIC_VECTOR( 1 DOWNTO 0);
	SUBTYPE UINT03  IS STD_LOGIC_VECTOR( 2 DOWNTO 0);
	SUBTYPE UINT04  IS STD_LOGIC_VECTOR( 3 DOWNTO 0);
	SUBTYPE UINT05  IS STD_LOGIC_VECTOR( 4 DOWNTO 0);
	SUBTYPE UINT06  IS STD_LOGIC_VECTOR( 5 DOWNTO 0);
	SUBTYPE UINT07  IS STD_LOGIC_VECTOR( 6 DOWNTO 0);
	SUBTYPE UINT08  IS STD_LOGIC_VECTOR( 7 DOWNTO 0);
	SUBTYPE UINT09  IS STD_LOGIC_VECTOR( 8 DOWNTO 0);
	SUBTYPE UINT10  IS STD_LOGIC_VECTOR( 9 DOWNTO 0);
	SUBTYPE UINT11  IS STD_LOGIC_VECTOR(10 DOWNTO 0);
	SUBTYPE UINT12  IS STD_LOGIC_VECTOR(11 DOWNTO 0);
	SUBTYPE UINT13  IS STD_LOGIC_VECTOR(12 DOWNTO 0);
	SUBTYPE UINT15  IS STD_LOGIC_VECTOR(14 DOWNTO 0);
	SUBTYPE UINT14  IS STD_LOGIC_VECTOR(13 DOWNTO 0);
	SUBTYPE UINT16  IS STD_LOGIC_VECTOR(15 DOWNTO 0);
	SUBTYPE UINT22  IS STD_LOGIC_VECTOR(21 DOWNTO 0);
	SUBTYPE UINT24  IS STD_LOGIC_VECTOR(23 DOWNTO 0);
	SUBTYPE UINT32  IS STD_LOGIC_VECTOR(31 DOWNTO 0);
	SUBTYPE INT04K  IS INTEGER RANGE 0 TO 4095     ;
	
--	TYPE    COLOR_T IS RECORD
--		R     : UINT08;
--		G     : UINT08;
--		B     : UINT08;
--	END RECORD COLOR_T;
	
	CONSTANT NO_ADDR : UINT12 := (OTHERS => '0');
	
--	CONSTANT WHITE : COLOR_T :=
--	(
--		R => "11111111",
--		G => "11111111",
--		B => "11111111"
--	);
--	
--	CONSTANT BLACK : COLOR_T :=
--	(
--		R => "00000000",
--		G => "00000000",
--		B => "00000000"
--	);
	
	PURE FUNCTION Slv2Int (INPUT : STD_LOGIC_VECTOR)
	RETURN INTEGER;
	
	PURE FUNCTION Int2Slv (INPUT : INTEGER; LENGTH : NATURAL)
	RETURN STD_LOGIC_VECTOR;
	
END PACKAGE basic_package;
------------------------------------------------------
PACKAGE BODY basic_package IS
	
	PURE FUNCTION Slv2Int (INPUT : STD_LOGIC_VECTOR)
	RETURN INTEGER IS
	BEGIN
		RETURN TO_INTEGER(UNSIGNED(INPUT));
	END Slv2Int;
	
	PURE FUNCTION Int2Slv (INPUT : INTEGER; LENGTH : NATURAL)
	RETURN STD_LOGIC_VECTOR IS
	BEGIN
		RETURN STD_LOGIC_VECTOR(TO_UNSIGNED(INPUT, LENGTH));
	END Int2Slv;
	
END basic_package;
